config/routes.rb
Rails.application.routes.draw do
root to: 'users#new'
resources :optimes, :users
get 'result', to: "optimes#result"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/optime.rb
class Optime < ApplicationRecord
    belongs_to :user
    validates :sleepy, presence: true
    validates :work, presence: true
    validates :commute, presence: true
    validates :eat, presence: true
    validates :hygiene, presence: true
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :optimes, dependent: :destroy
    validates :guest_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/optimes_controller.rb
class OptimesController < ApplicationController
  def index
    @optimes = Optime.page(params[:page]).per(6).includes(:user).order(created_at: :desc)
    @user = User.last
  end

  def show
    @user = User.find(params[:id])
    @optimes = Optime.find(params[:id])
  end
  def new
    @user = User.last
    @optime = Optime.new
  end

  def create
    @user = User.last
    @optime= @user.optimes.build(optime_params)
    if @optime.save
      redirect_to  result_path 
    else
      render :new
    end
  end

  def result
    @user = User.last
    @optime = Optime.last
  end

  private

  def optime_params
    params.require(:optime).permit(:guest_name,:title,:sleepy, :eat, :work, :commute, :hygiene)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 def index
 end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to new_optime_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:guest_name,:email, :password, :password_confirmation, :last_name, :first_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
        
        if @user.save
          redirect_to new_optime_path
        else
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:guest_name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/optimes_helper.rb
module OptimesHelper
    def sum_of_undisposable(optimes)
        "　#{24 - (optimes.sleepy + optimes.work + optimes.eat + optimes.commute + optimes.hygiene) } 時間"
    end

    def good_sleep(optimes)
        if optimes.sleepy == 0
          return "いくらなんでも寝てくださいね、、体あっての仕事ですよ、、転職しましょうよ、、、"
        elsif optimes.sleepy <= 3
          return "流石にショートスリープすぎません？睡眠時間の確保できる会社に転職しましょうか。"
        elsif　optimes.sleepy <= 6
          return "最低でも7時間は寝たいですね。勤務時間が短い会社に転職しましょうか。"
        else
          return "ぐっすり眠れてますか？睡眠の質を高めるために転職しましょうか。"
        end
     end
    def good_commute(optimes)
        if optimes.commute == 0
          return "リモートワークっすか！いいですね〜。でも人肌恋しくありません？転職しましょ？"
        elsif optimes.commute == 1
          return "お仕事お疲れ様です。満員電車に悩みはありませんか？引っ越しも考えましょうか。"
        else
          return "職場まで遠いと感じませんか?引っ越しも考えましょうか。"
        end
     end
    def good_work(optimes)
        if optimes.work == 0
          return "働いてないんですか？逆に暇ですよね。求職しましょ。"
        elsif optimes.work <= 7
          return "業務効率化が計れていますね。ワークライフバランスが取れていて何よりです。"
        elsif optimes.work <= 9
          return "働きすぎじゃないですか？勤務時間が短くて年収の高い会社に転職しましょうか。" 
        else optimes.work  >=10
          return "ちょ、働きすぎですよまじで。転職しましょ。"
        end
     end
    def good_eat(optimes)
        if optimes.eat == 0
          return "流石に何か食べないと死にますよ、、食事の時間が取れるくらいに勤務時間の短い会社に転職しましょ？"
        elsif optimes.eat >= 2
          return "優雅に食事を楽しめてますね。"
        else
          return "よくかんで食べれてますか？食事の時間が取れるくらいに勤務時間の短い会社に転職しましょうか。" 
        end
     end
    def good_hygiene(optimes)
        unless optimes.hygiene >= 2
          return "清潔ですね。運動時間も確保できると最高ですね。"
        else
          return "自分を磨けてますか？自分の時間を確保できるくらい勤務時間の短い会社に転職しましょうか。" 
        end
     end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OptimeAnalyze</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-LD6CZVX3XD"></script>
   <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

    gtag('config', 'G-LD6CZVX3XD');
   </script>
  </head>

  <body>
   <%= render 'shared/header'%>
    <%= yield %>
  </body>
    <%= render 'shared/footer'%>
</html>

app/views/optimes/_form.html.erb
<%= form_with model: optime, html: { class: 'text-center mt-3' },  local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.date_field :title,selected: optime.title, class: 'form-control text-center mt-3 ' %>
        </div>
        <div class="form-group">
          <%= f.label :sleepy ,class: "subject"%>
          <%= f.select :sleepy, 
          options_for_select([
         ['睡眠時間を入力', ''], 
         ['0', '0'], 
          ['1', '1'], 
          ['２', '２'], 
          ['3', '3'], 
          ['4', '4'], 
          ['5', '5'], 
          ['6', '6'], 
          ['7', '7'], 
          ['8', '8'], 
          ['9', '9'], 
          ['10', '10'], 
          ['11', '11'], 
          ['12', '12'],
          ['13', '13'],
          ],selected: optime.sleepy), {}, {class: 'optime__select'} %>

        </div>
        <div class="form-group">
         <%= f.label :commute ,class: "subject"%>
    <%= f.select :commute, 
       options_for_select([
       ['通勤時間（往復）を入力', ''], 
       ['0', '0'], 
       ['1', '1'], 
       ['2', '2'], 
       ['3', '3'],
       ['4', '4'],
       ['5', '5'],
       ],selected: optime.commute), {}, {class: 'optime__select'} %>
        </div>
        <div class="form-group">
        <%= f.label :work ,class: "subject"%>
    <%= f.select :work, 
       options_for_select([
       ['勤務時間を入力', ''], 
       ['0', '0'], 
       ['1', '1'], 
       ['2', '2'], 
       ['3', '3'],
       ['4', '4'],
       ['5', '5'],
       ['6', '6'],
       ['7', '7'],
       ['8', '8'],
       ['9', '9'],
       ['10', '10'],
       ['11', '11']
       ],selected: optime.work), {}, {class: 'optime__select'} %>
        </div>
        <div class="form-group">
       <%= f.label :eat ,class: "subject"%>
    <%= f.select :eat, 
       options_for_select([
       ['食事時間を入力', ''],
       ['0', '0'], 
          ['1', '1'], 
       ['2', '2'], 
       ['3', '3'],
       ['4', '4'],
       ['5', '5'],
       ['6', '6'],
       ['7', '7'],
       ['8', '8'],
       ['9', '9'],
       ['10', '10'],
       ['11', '11']
       ],selected: optime.eat), {}, {class: 'optime__select'} %>
        </div>
        <div class="form-group">
    <%= f.label :hygiene ,class: "subject"%>
    <%= f.select :hygiene, 
       options_for_select([
       ['衛生（風呂歯磨きトイレ）時間を入力', ''], 
       ['0', '0'], 
          ['1', '1'], 
       ['2', '2'], 
       ['3', '3'],
       ['4', '4'],
       ['5', '5'],
       ['6', '6'],
       ['7', '7'],
       ['8', '8'],
       ['9', '9'],
       ['10', '10'],
       ['11', '11']
       ],selected: optime.hygiene), {}, {class: 'optime__select'} %>
        </div>
        <div class="actions">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/optimes/_optime.html.erb
<div class="card text-center text-dark border-warning mb-3" style="max-width: 18rem;">
<p class ="text-center mb-3 mt-4 border-bottom card-content"><%=  "#{optime.user.guest_name}さん"%></p>
  <div class="card-header"> 
    <h5 class="card-title text-center"><%= link_to optime.title, optime_path(optime) %><br>
  </h5>
  </div>
  <div id="optime-id-<%= optime.id %>">
  <div class="card-body">
        <p class="card-text"><%= "睡眠: #{optime.sleepy}時間" %></p>
        <p class="card-text"><%= "仕事: #{optime.work}時間" %></p>
        <p class="card-text"><%= "食事: #{optime.eat}時間"%></p>
        <p class="card-text"><%= "通勤: #{optime.commute}時間" %></p>
        <p class="card-text"><%= "衛生管理: #{optime.hygiene}時間" %></p>
  </div>
</div>
</div>

app/views/optimes/_result.html.erb
<div class="container">
<h1 class="text-center title">診断結果</h1>
  <div class ="text-center title ">
    <%= link_to 'Share', "https://twitter.com/share?url=https://caloptime.herokuapp.com&text=【#{@user.guest_name}さんの可処分時間】は%0a#{sum_of_undisposable(optime)}でした。
      %0a固定時間内訳:　
      %0a睡眠：#{optime.sleepy}時間
      %0a食事：#{optime.eat}時間
      %0a衛生時間：#{optime.hygiene}時間
      %0a通勤時間：#{optime.commute}時間
      %0a勤務時間：#{optime.work}時間
      %0a@247subaru%20%23Optime%20%20%23人生100年時代%20",
      title: 'Twitter',class:'fab fa-twitter', target: '_blank' %>
  </div>

    <div class="bg-white" style="border-radius: 100px; ">
      <h2 class="text-center mb-3 mt-4"><%= @user.guest_name%>さんの可処分時間は<br>
        <span class="big"><%= sum_of_undisposable(optime) %></span>です</h2>
          <h2 class="text-center mb-3 mt-4">人生100年時代、<span class="big"><%= sum_of_undisposable(optime) %></span>を何に充てる?</h2>
    </div>
    <div class ="image_new d-flex justify-content-between">
      <div>
        <p>瞑想？</p>
          <%= image_tag 'meditate.svg',name: '瞑想にする？'%>
      </div>
      <div class="not_show" >
        <p>仕事？</p>
          <%= image_tag 'work.svg'%>
      </div>
      <div class="not_show" >
        <p>ダンス？</p>
         <%= image_tag 'dance.svg'%>
      </div>
      <div>
        <p class="not_show" >お絵描き？</p>
        <%= image_tag 'drawing.svg'%>
      </div>
      <div>
        <p>筋トレ？</p>
        <%= image_tag 'gym.svg'%>
    </div>
</div>
  <div class ="chart_area mp-3">
    <canvas id="myChart" ></canvas> 
  </div>
    <div class="text-center wrapper mb-3 mt-4">
      <h2  class="text-center title" >固定時間削減方法</h2>
        <ul>
            <li><p class="optime subtitle border-bottom" >睡眠時間</p><span class="optime__select"><%= optime.sleepy %></span>時間</li>
              <li class="mb-4 comment"><%= good_sleep(optime)%></li>

            <li><p class="optime subtitle border-bottom ">勤務時間</p><span class="optime__select"><%=optime.work%></span>時間</li>
              <li class="mb-4 comment"><%= good_work(optime)%></li>
       
            <li><p class="optime subtitle border-bottom">食事時間</p><span class="optime__select"><%=optime.eat%></span>時間</li>
              <li class="mb-4 comment"><%= good_eat(optime)%></li>
       
            <li><p class="optime subtitle border-bottom">通勤時間</p><span class="optime__select"><%=optime.commute%></span>時間</li>
              <li class="mb-4 comment"><%= good_commute(optime)%></li>
       
            <li><p class="optime subtitle border-bottom">衛生管理時間</p><span class="optime__select"><%=optime.hygiene%></span>時間</li>
              <li class="mb-4 comment"><%= good_hygiene(optime)%></li>
        </ul>
    </div>
</div>

<script>
 //ページ内の科目を取得
    var subject01 = document.querySelectorAll('.optime')[0].innerHTML,
        subject02 = document.querySelectorAll('.optime')[1].innerHTML,
        subject03 = document.querySelectorAll('.optime')[2].innerHTML,
        subject04 = document.querySelectorAll('.optime')[3].innerHTML,
        subject05 = document.querySelectorAll('.optime')[4].innerHTML,

        //ページ内の数値を取得
        subjectnum01 = document.querySelectorAll('.optime__select')[0].innerHTML,
        subjectnum02 = document.querySelectorAll('.optime__select')[1].innerHTML,
        subjectnum03 = document.querySelectorAll('.optime__select')[2].innerHTML,
        subjectnum04 = document.querySelectorAll('.optime__select')[3].innerHTML,
        subjectnum05 = document.querySelectorAll('.optime__select')[4].innerHTML;
            //取得した科目と数値をChart.jsに入れる
    var data = {
        labels: [subject01, subject02, subject03, subject04, subject05],
        datasets: [{
            label: '可処分時間項目',
            data: [subjectnum01, subjectnum02, subjectnum03, subjectnum04, subjectnum05],
            backgroundColor: ['rgb(248, 252, 8)','rgb(162, 226, 89)','rgb(253, 237, 15)','rgb(228, 230, 141)','rgb(89, 226, 203)'],
            borderColor: 'rgba(255,135,0,1)',
            pointBackgroundColor: 'rgba(255,135,0,1)',
            pointBorderColor: 'rgba(255,135,0,0)',
            pointBorderWidth: 0,
            pointRadius: 5,
            pointStyle: 'circle',
            pointHoverRadius: 5,
            pointHitRadius: 5
        }]
    };
var ctx = document.getElementById('myChart').getContext('2d');
var myChart   = new Chart(ctx, {
        type: 'doughnut',
        data: data,
        options: {
            title: {
                display: true,
                text: '固定時間内訳',
                padding: 4,
                fontSize: 20
            },
            legend: {
                text: '固定時間内訳',
                display: false,
                labels: {
                    fontColor: 'rgb(5, 99, 132)',
                    fontSize: 16
                }
            },
            scale: {
                pointLabels: {
                    fontSize: 15,
                    fontColor: 'rgb(0, 65, 112)',
                    padding: 20
                },
                ticks: {
                    beginAtZero: true,
                }
            },
            layout: {
                padding: {
                    left: 0,
                    right: 0,
                    top: 0,
                    bottom: 0
                }
            },
            maintainAspectRatio: false,
        }
    });
</script>

app/views/optimes/index.html.erb
<div class="card-deck">
    <div class="col-12">
      <div class="row">
        <% if @optimes.present? %>
          <%= render @optimes %>
        <% else %>
       <%= image_tag 'noposts.jpeg' %>
        <% end %>
      </div>
    </div>
  </div>
         <%= paginate @optimes, left: 1, right: 3 %>
</div>
 
</div>

app/views/optimes/new.html.erb
<h1 class ="text-center mb-3 mt-4"><%= @user.guest_name%>さんの可処分時間を計算する</h1>

<%= render 'form', {optime: @optime}%>

<%= link_to 'Back', optimes_path %>

app/views/optimes/result.html.erb
<%= render 'result', {optime: @optime, user: @user}%>
<div class="d-flex justify-content-between">
  <%= link_to 'もう一回診断する',new_user_path %>
  <%= link_to 'みんなの可処分時間',optimes_path %>
</div>

app/views/optimes/show.html.erb
<%# <%= render 'result', {optime: @optimes, user: @user} %> %>
<div class="text-center"> <%= link_to 'みんなの可処分時間',optimes_path %></div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class ="alert alert-danger">
    <ul class="mb-0">
    <% object.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
        <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_footer.html.erb
<footer class ="text-center bg-dark text-light">© 2021 Subaru All Rights Preserved.</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
   <%= link_to 'Optime', root_path, class: 'navbar-brand'%>
    <ul class="navbar-nav mr-auto mt-2 mt-lg">
      <li class="nav-item">
      <%= link_to 'みんなの可処分時間',optimes_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/static_pages/index.html.erb
<div class="container">
<h1 class ="text-center mb-3 mt-4">Calculate Optime</h1>
<p class ="text-center mb-3 mt-4">可処分時間を計算しよう</p>
<p class ="ext-center mb-3 mt-4">可処分時間とは何か</p>
<div class="text-center mb-3 mt-4 d-flex justify-content-space-between">
 <%= image_tag 'meditate.svg',name: '瞑想にする？'%>

 <div class = "d-flex justify-content-space-between">
 <%= link_to 'ユーザー登録',new_static_page_path %>
 <%= link_to 'ゲストユーザー', new_guest_user_path %>
 </div>
 </div>

<%= link_to '既にアカウントをお持ちの方',login_path%>


</div>

app/views/users/new.html.erb
<div class="container">
<h1 class ="text-center mb-3 mt-4">Calculate Optime</h1>
<p class ="text-center mb-3 mt-4">可処分時間を計算しよう</p>
  <div class ="image_new d-flex justify-content-between col-md-3　col-xs-6">
      <%= image_tag 'food.svg',name: '飯',class: 'not_show'%>
      <%= image_tag 'commute.svg',name: '通勤',class: 'not_show'%>
      <%= image_tag 'sleep.svg',name: '睡眠'%>
      <%# <%= image_tag 'work.svg',name: '勤務'%>
      <%= image_tag 'hygiene.svg',name: '衛生'%> 
</div>
<p class = "text-center">お名前を入力してください。</p>

<%= form_with model: @user, html: { class: 'text-center mt-3' },  local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
     <div class="form-group ms-4">
       <%= f.label :guest_name %>
       <%= f.text_field :guest_name, class: 'form-control text-center', id: 'user_last_name'%>
     </div>
     <div class="actions">
       <%= f.submit '登録', class: 'btn btn-primary' %>
     </div>
     <%end%>

</div>